name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      playwright_version: ${{ steps.get_playwright_version.outputs.playwright_version }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
      - uses: actions/checkout@v6
      - id: get_playwright_version
        run: |
          VERSION=$(jq -r '.devDependencies["@playwright/test"]' package.json)
          # Strip ^ or ~ if present
          CLEAN_VERSION=$(echo "$VERSION" | sed 's/^[^0-9]*//')
          echo "playwright_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
  ci:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      PUBLIC_SITE_ENV: ci
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run build-storybook
      - run: npm run check
      - run: npm run test:unit:coverage
      - name: Upload unit coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit
          files: coverage/unit/coverage-final.json
  ci-e2e:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      PUBLIC_SITE_ENV: ci
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.pre_job.outputs.playwright_version }}-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci
      - run: npm run test:e2e
      - run: npm run test:storybook:coverage
      - name: Upload storybook coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: storybook
          files: coverage/storybook/coverage-final.json
